name: package

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'test_package/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - 'tools/**'
      - 'tests/**'
      - 'npm-package.yml'
    branches:
      - main
      - dev
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - 'GH-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
  conan-package:
    uses: ultimaker/libnest2d/.github/workflows/conan-package.yml@main

  npm-package:
    needs: [ conan-package ]
    uses: ultimaker/cura-workflows/.github/workflows/npm-package.yml@main
    with:
      package_version_full: ${{ needs.conan-package.outputs.package_version_full }}
    secrets: inherit
