name: package

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'test_package/**'
      - 'tests/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - 'requirements.txt'
      - '.github/workflows/package.yml'
      - '.github/workflows/requirements*'
      - 'libnest2d_js/**'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@main
    with:
      platform_wasm: true
    secrets: inherit

  npm-package:
    needs: [ conan-package ]
    uses: ultimaker/cura-workflows/.github/workflows/npm-package.yml@main
    with:
      package_version_full: ${{ needs.conan-package.outputs.package_version_full }}
    secrets: inherit