---
name: unit-test
# FIXME: This should be a reusable workflow

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'tests'
      - 'test_package/**'
      - 'tests/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - 'requirements.txt'
      - '.github/workflows/unit-test.yml'
      - '.github/workflows/requirements*'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'tests'
      - 'test_package/**'
      - 'tests/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - 'requirements.txt'
      - '.github/workflows/unit-test.yml'
      - '.github/workflows/requirements*'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

permissions:
  contents: read

env:
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASS }}

jobs:
  conan-recipe-version:
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@main
    with:
      project_name: nest2d

  testing:
    uses: ultimaker/cura-workflows/.github/workflows/unit-test.yml@main
    needs: [ conan-recipe-version ]
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      conan_extra_args: '-c tools.build:skip_test=False'
      unit_test_cmd: 'ctest --output-junit engine_test.xml'
      unit_test_dir: 'build/Release'
      build: true
    secrets: inherit
